### ISSUE TITLE
Typo in file

### ISSUE THREAD

**Issue by paulwaddington** [selvinortiz/craft-plugin-shield#2]
### Describe the bug

Forms won't submit

### Steps to reproduce

File needs to be changed on line 154 from 'saveLod' to 'saveLog'

verb/shield/src/services/Service.php

### Craft CMS version

3.7.53.1

### Plugin version

2.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/shield/releases/tag/2.0.1)
