### ISSUE TITLE
Cannot assign array to property

### ISSUE THREAD

**Issue by paulwaddington** [selvinortiz/craft-plugin-shield#3]
### Describe the bug

Hi there! I get the error below when making 'logSubmissions' 'true':

Cannot assign array to property verbb\shield\models\Log::$content of type ?string

### Steps to reproduce

You can see the form here:

https://testing.avocet-dyes.ddme.design/contact-us

### Craft CMS version

4.4.8

### Plugin version

3.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/shield:"dev-craft-4 as 3.0.1`

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/shield/releases/tag/3.0.2)
